export const USERS_URL="/api/user"
export const ADMIN_URL="/api/admin"
export const PRODUCTS_URL="/api/products"
export const CART_URL="/api/cart"
export const WISHLIST_URL="/api/wishlist"
export const ORDERS_URL="/api/orders"